# The code is generated by ChatGPT

import matplotlib.pyplot as plt
import numpy as np

lr = [0.1, 0.2, 0.3, 0.4, 0.5,
      0.6, 0.8, 1,
      1.2,1.4,1.6,1.8, 2]
acc = [58.55, 59.75, 60.73, 60.76, 60.69
       ,60.65,60.51 , 61.27,
      60.09, 57.93 , 56.88 , 51.87 , 46.87]


# x_ticks = np.arange(len(lr))
plt.xticks(lr)

plt.plot(lr, acc, marker='o')
plt.xlabel('lr')
plt.ylabel('Accuracy')
plt.title('Learning Rate vs Accuracy')
plt.grid(True)


plt.show()

plt.savefig('plot_lr.png', bbox_inches='tight')

